name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Compilar com Buildozer Action
        uses: ArcturusZhang/buildozer-action@v1
        with:
          command: buildozer android debug

      - name: Enviar o APK pronto para download
        uses: actions/upload-artifact@v4
        with:
          name: Meu-Aplicativo-APK
          path: bin/*.apk
