name: Criar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Build com Buildozer
      uses: ArtemShatalov/buildozer-action@v1.3.0
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload do APK
      uses: actions/upload-artifact@v4
      with:
        name: Meu-Aplicativo-APK
        path: bin/*.apk
